# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAi < Formula
  desc "AI-powered Git commit message enhancer"
  homepage "https://github.com/daidi/git-ai"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daidi/git-ai/releases/download/v0.3.1/git-ai_darwin_amd64.tar.gz"
      sha256 "cc8bef2d92fe5d97fc72fde6e95bdd3eebafe0c4150830b0b989de7b4c11fda7"

      define_method(:install) do
        bin.install "git-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daidi/git-ai/releases/download/v0.3.1/git-ai_darwin_arm64.tar.gz"
      sha256 "584349fa43fd57217659e26206568c702ff9c6abacd2b769d6c718a2fee533fc"

      define_method(:install) do
        bin.install "git-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daidi/git-ai/releases/download/v0.3.1/git-ai_linux_amd64.tar.gz"
      sha256 "1e309d45e4d7bad00ab6a3ccff5e8a5ae1fd88bfc7b4dc0b232a65c03bcef1f9"
      define_method(:install) do
        bin.install "git-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daidi/git-ai/releases/download/v0.3.1/git-ai_linux_arm64.tar.gz"
      sha256 "dc0dd5dcd4179f1bfe4d27589b58123a1f4206e25ba512aedbf693e6ee0929ee"
      define_method(:install) do
        bin.install "git-ai"
      end
    end
  end
end
